# Sem mais majors (que costumam quebrar o build).
# Só 3 PRs mensais para você analisar.
# Patch/minor que passam nos checks vão mergear sozinhos.

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@types/react-*"
        update-types:
          - "version-update:semver-major"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type:
            - "version-update:semver-patch"
            - "version-update:semver-minor"
